# Iceberg Dark ANSI palette.
# Source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/schemes/Iceberg%20Dark.itermcolors

set -s theme terminal

set -g pane-colours[0] '#1e2132'
set -g pane-colours[1] '#e27878'
set -g pane-colours[2] '#b4be82'
set -g pane-colours[3] '#e2a478'
set -g pane-colours[4] '#84a0c6'
set -g pane-colours[5] '#a093c7'
set -g pane-colours[6] '#89b8c2'
set -g pane-colours[7] '#c6c8d1'
set -g pane-colours[8] '#6b7089'
set -g pane-colours[9] '#e98989'
set -g pane-colours[10] '#c0ca8e'
set -g pane-colours[11] '#e9b189'
set -g pane-colours[12] '#91acd1'
set -g pane-colours[13] '#ada0d3'
set -g pane-colours[14] '#95c4ce'
set -g pane-colours[15] '#d2d4de'

set -g pane-border-style 'fg=black'
set -g pane-active-border-style 'fg=magenta'
